### ISSUE TITLE
master is broken: Uncaught TypeError: Cannot set property 'colorpicker' of undefined

### ISSUE THREAD

**Issue by itsjavi** [farbelous/bootstrap-colorpicker#286]
### Description

After changes introduced in #285 , the plugin does not work in browsers:

`Uncaught TypeError: $(...).colorpicker is not a function`
`Uncaught TypeError: Cannot set property 'colorpicker' of undefined`

### Context

- bootstrap-colorpicker version: https://github.com/farbelous/bootstrap-colorpicker/commit/f7e626615556858438842888de31ca59faa5602f
- bootstrap version: 4.1.3
- jQuery version: 3.3.1
- Browser name and version: Chrome 70
- Operative System name an version: macOS Mojave

### Expected behavior

Plugin working in both nodejs and browsers

### Actual behavior

Plugin broken in browsers

### Live Example

Has to be tested locally:
- Clone the project on master (commit f7e626615556858438842888de31ca59faa5602f)
- Run `npm run build`
- Run `npm start`
- Go to `http://127.0.0.1:8080/` and check the browser console

**Comment by mathieupotier** [comment]
I'll check this out ASAP

**Comment by mathieupotier** [comment]
repaired in https://github.com/farbelous/bootstrap-colorpicker/pull/288
